### ISSUE TITLE
No extension found for oid on column with function in SELECT

### ISSUE THREAD

**Issue by simonprev** [ericmj/postgrex#106]
Hi,

I’ve been trying to implement a full text search using postgresql. But when I try tu run a simple query with the `to_tsvector` function, the query raises on error. I call the `postgrex` lib from `ecto`. Here is the simplest example to reproduce the behavior.

```elixir
query = """
select to_tsvector('simple', translations.key) from translations
"""

Ecto.Adapters.SQL.query(MyApp.Repo, query, [])
```

And the stacktrace:

```shell
** (exit) exited in: Postgrex.Connection.query(#PID<0.1096.0>, "select to_tsvector('simple', translations.key) from translations\n", [], [timeout: 5000])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) no extension found for oid `3614`
            (postgrex) lib/postgrex/types.ex:284: Postgrex.Types.fetch!/2
            (postgrex) lib/postgrex/types.ex:213: Postgrex.Types.format/2
            (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
            (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
            (elixir) lib/enum.ex:1043: Enum.map/2
            (postgrex) lib/postgrex/protocol.ex:72: Postgrex.Protocol.message/3
            (postgrex) lib/postgrex/connection.ex:361: Postgrex.Connection.new_data/2
            (postgrex) lib/postgrex/connection.ex:265: Postgrex.Connection.handle_info/2
```

`postgrex` seems to build a table with a mapping and cast of each column. So when it tries to find to mapping of the `to_tsvector`’s result, it fails here `lib/postgrex/types.ex#L280`

Thanks for your help!

**Comment by josevalim** [comment]
@simonprev postgrex doesn't know how to encode all database types, specially because anyone can define any type for postgres. Read the session on Extensions and OID in the README about implementing your own. Maybe someone else already solved this problem too, so I would ask the elixir mailing list as well (which is the recommended place for questions).

**Comment by simonprev** [comment]
I created an issue because I mistakenly thought that it was a bug :disappointed: I’ll be sure to check the mailing list next time :+1: Thanks for the quick response!

**Comment by madshargreave** [comment]
Did you find a solution to this?
