### ISSUE TITLE
Missing encoder for float8

### ISSUE THREAD

**Issue by almassapargali** [ericmj/postgrex#123]
Hello, I'm using [earthdistance](http://www.postgresql.org/docs/8.3/static/earthdistance.html) module for querying users by coordinates, and I'm getting this error when passing `String`. If I convert input to `float` or `integer` myself and query, then all is good. Here is the log:
```
Request: GET /users/nearby?longitude=42.6&latitude=12.3
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Postgrex.Extensions.Binary.encode/4
        (postgrex) lib/postgrex/extensions/binary.ex:59: Postgrex.Extensions.Binary.encode(%Postgrex.TypeInfo{array_elem: 0, base_type: 0, comp_elems: [], input: "float8in", oid: 701, output: "float8out", receive: "float8recv", send: "float8send", type: "float8"}, "12.3", 901179, {9, 4, 5})
```

I wanted to fix this myself, and send PR, but not that good in binary `<< :: :D >>` stuff yet, sorry :smile:

**Comment by josevalim** [comment]
It is not about a missing encoder. You are sending a string to a float or integer column, then Postgres is giving up because it doesn't know how you would parse that.  I believe converting it to integer or float is the way to go. :)

**Comment by almassapargali** [comment]
Oh sorry, just ecto was handling my other string to int conversions well, so I though float one is missing.
