### ISSUE TITLE
Postgrex.Connection kills application on connection refused

### ISSUE THREAD

**Issue by andreihu** [ericmj/postgrex#124]
Hi Eric,

 I am trying to integrate a Postgrex.Connection into my gen_fsm module. The init/1 function looks like this:

	#### gen_fsm implementation
	def init(params) do
		try_connect_backend(params)
	end

	defp try_connect_backend(params) do
		case Postgrex.Connection.start_link(hostname: params.host, username: params.user, password: params.pass, database: "spoold") do
			{:ok, conn} ->
				Logger.info("connected to database backend")
				{:ok, :connected, %{:conn => conn, :params => params}, @timeouts.connected}
			{:error, err} ->
				Logger.warn("failed to connect to database backend: #{err}")
				{:ok, :errored, %{:params => params}, @timeouts.errored}
		end
	end

In laymens term i'd like to have a connected and an errored state for my fsm representing whether i have a db connection or not. However it's not working as expected. When i run the application, i got the following (i am testing with a database server offline, to see whether the fsm entering errored state):

Compiled lib/spoold_worker.ex
Generated spoold app

14:18:12.404 [info]  connected to database backend
Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
14:18:12.437 [info]  connected to database backend
14:18:12.445 [info]  connected to database backend
14:18:12.450 [info]  connected to database backend
14:18:12.450 [error] GenServer #PID<0.143.0> terminating
** (stop) %Postgrex.Error{message: "tcp connect: connection refused - :econnrefused", postgres: nil}
Last message: nil
State: [password: :REDACTED, hostname: "devserver", username: "spoold", database: "spoold"]

14:18:12.454 [error] GenServer #PID<0.149.0> terminating
** (stop) %Postgrex.Error{message: "tcp connect: connection refused - :econnrefused", postgres: nil}
Last message: nil
State: [password: :REDACTED, hostname: "devserver", username: "spoold", database: "spoold"]

14:18:12.458 [error] GenServer #PID<0.151.0> terminating
** (stop) %Postgrex.Error{message: "tcp connect: connection refused - :econnrefused", postgres: nil}
Last message: nil
State: [password: :REDACTED, hostname: "devserver", username: "spoold", database: "spoold"]

14:18:12.461 [error] GenServer #PID<0.153.0> terminating
** (stop) %Postgrex.Error{message: "tcp connect: connection refused - :econnrefused", postgres: nil}
Last message: nil
State: [password: :REDACTED, hostname: "devserver", username: "spoold", database: "spoold"]

14:18:12.461 [info]  Application spoold exited: shutdown

So somehow i get back {:ok, pid} from Postgrex.Connection.start_link, but after that Postgrex blows up several times (with the expected error) and my application shuts down.

I am new to elixir, so most likely i am doing something wrong, but i am out of ideas here. Could you tell me how could i catch the error?

Thanks
 Andras

**Comment by josevalim** [comment]
Welcome to Elixir @andreihu!

Could you please take your questions to the elixir-talk mailing list? There are a lot of folks who could help you there and this way we don't need to depend on @ericmj in particular to answer your questions.

Thank you!
