### ISSUE TITLE
Adding support for Geometric Types

### ISSUE THREAD

**Issue by jbavari** [ericmj/postgrex#125]
First off, thanks @ericmj for the excellent library. It's great.

I'm trying to add support to postgrex to handle the [geometric types](http://www.postgresql.org/docs/9.4/static/datatype-geometric.html#AEN6730).

These are basic types and I'm trying to use them for distance calculations outside of moving to postgis.

I'd love to add support for these types. However, I'm still relatively new to Elixir, and could use some guiding points.

First i've added a test in `query_test.exs`:

```
test "decode point", context do
  assert [[-97, 100]] == query("SELECT point(-97, 100)::point", [])
end
```

Right away, I get this error:

```
1) test decode point (QueryTest)
     test/query_test.exs:112
     ** (ArgumentError) no extension found for oid `600`
     stacktrace:
       (postgrex) lib/postgrex/types.ex:296: Postgrex.Types.fetch!/2
       (postgrex) lib/postgrex/types.ex:220: Postgrex.Types.decoder/2
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1043: Enum.map/2
       (postgrex) lib/postgrex/protocol.ex:592: Postgrex.Protocol.decoders/2
       (postgrex) lib/postgrex/protocol.ex:415: Postgrex.Protocol.describe_results/5
       (postgrex) lib/postgrex/protocol.ex:64: Postgrex.Protocol.query/4
       (postgrex) lib/postgrex/connection.ex:352: Postgrex.Connection.run/5
       (postgrex) lib/postgrex/connection.ex:343: Postgrex.Connection.run/3
       test/query_test.exs:113
```

As I said, i'm still pretty green to this!

I tried defining a module:

```
defmodule Postgrex.Point do
  @moduledoc """
  Struct for Postgres point.

  ## Fields
    * `x`
    * `y`
  """
  @type t :: %__MODULE__{x: :x, y: :x}

  defstruct [
    x: nil,
    y: nil]
end
```

I also saw the `extensions`, and wasn't sure if I needed to add it as an extension or just leave it as a base type, which I assumed it was.

Are there any pointers you'd help guide me in the right direction?

**Comment by evax** [comment]
This library by @bryanjos is implementing what you need:
https://github.com/bryanjos/geo

**Comment by josevalim** [comment]
Yes, we leave it up for third party to extend postgrex with custom types. :)

**Comment by jbavari** [comment]
@evax @josevalim 

I should have stated before, I was trying to use the Geo library.

However, I'm not using the custom types provided by PostGIS. I'm attempting to use the native geometric types provided by postgres. ([See this link for more info](http://www.postgresql.org/docs/9.4/static/datatype-geometric.html#AEN6730))

When using these native geometric types, postgrex still errors out.

Here's what I'm working with:

Model:
```
defmodule MyApp.Concert do
  use MyApp.Web, :model

  schema "concerts" do
    field :name, :string
    field :date, Ecto.DateTime
    field :location, Geo.Point
    timestamps
  end
end
```

Config:
```
config :myapp, MyApp.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "myapp_dev",
  hostname: "localhost",
  extensions: [{Geo.PostGIS, library: Geo}],
  pool_size: 10

```

Table:
```
┌─────────────┬─────────────────────────────┬───────────────────────────────────────────────────────┐
│   Column    │            Type             │                       Modifiers                       │
├─────────────┼─────────────────────────────┼───────────────────────────────────────────────────────┤
│ id          │ integer                     │ not null default nextval('concerts_id_seq'::regclass) │
│ name        │ character varying(255)      │                                                       │
│ date        │ timestamp without time zone │                                                       │
│ inserted_at │ timestamp without time zone │ not null                                              │
│ updated_at  │ timestamp without time zone │ not null                                              │
│ location    │ point                       │                                                       │
└─────────────┴─────────────────────────────┴───────────────────────────────────────────────────────┘

```

iex:

```
iex(1)> alias MyApp.Repo
nil
iex(2)> alias MyApp.Concert 
nil
iex(3)> Repo.all(Concert)
** (ArgumentError) no extension found for oid `600`
    (postgrex) lib/postgrex/types.ex:280: Postgrex.Types.fetch!/2
    (postgrex) lib/postgrex/types.ex:213: Postgrex.Types.format/2
      (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
      (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
      (elixir) lib/enum.ex:1043: Enum.map/2
    (postgrex) lib/postgrex/protocol.ex:134: Postgrex.Protocol.message/3
    (postgrex) lib/postgrex/connection.ex:417: Postgrex.Connection.new_data/2
    (postgrex) lib/postgrex/connection.ex:292: Postgrex.Connection.handle_info/2
      (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
      (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
      (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
iex(3)> 
```

As you can see, even using the Geo library thats provided (and is awesome), it's still failing to pick up the correct OID for point.

I'm sure I'm doing something wrong, and I am hoping I'm not bothering you all or poking around in the wrong place.

Does this change any thing or am I just barking up the wrong tree?

**Comment by ericmj** [comment]
The basic geometry types are built-in to postgres to if someone provides the PR we will merge it.

I took a brief look at @bryanjos geo library and it does not seem to support the types here: http://www.postgresql.org/docs/9.4/static/datatype-geometric.html. It only supports the `geometry` and `geography` types which I guess are PostGIS types?

**Comment by jbavari** [comment]
@ericmj I'd love to add this PR. I'd just need a little guidance on finishing it up.

As first posted, I've got the types put in place, the test set up.

My question is - where do I load the type with OID and the corresponding `_send` types?

**Comment by bryanjos** [comment]
@ericmj yes `geometry` and `geography` are PostGIS data types. I had no idea about the geometric data types native to postgres. They seem to be generic geometric types and not specialized for geospatial applications.

**Comment by ericmj** [comment]
@jbavari Check out the docs for extensions http://hexdocs.pm/postgrex/Postgrex.Extension.html. Also take a look at the extensions that ship with postgrex: https://github.com/ericmj/postgrex/tree/master/lib/postgrex/extensions.

**Comment by josevalim** [comment]
Keep in mind there was a bug in Ecto where we would not reset the OID stuff after migration. Be sure you are on latest Ecto. The bug will persist when running tests, the first time you run your tests it will fail with OID reason, the next time you should be fine though. We are working for a fix on the test scenario too.
