### ISSUE TITLE
PostgreSQL Type 2277 oid is not found

### ISSUE THREAD

**Issue by yoavlt** [ericmj/postgrex#130]
I use [PipelineDB](https://github.com/pipelinedb/pipelinedb) through this library.

I met an error around postgresql type. Its type is supported in other language driver (ex. https://github.com/lib/pq/blob/b269bd035a727d6c1081f76e7a239a1b00674c40/oid/types.go) How do I fix it?

Error message is the following.
```
      ** (EXIT) an exception was raised:
          ** (ArgumentError) no extension found for oid `2277`
              (postgrex) lib/postgrex/types.ex:280: Postgrex.Types.fetch!/2
              (postgrex) lib/postgrex/types.ex:213: Postgrex.Types.format/2
              (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
              (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
              (elixir) lib/enum.ex:1043: Enum.map/2
              (postgrex) lib/postgrex/protocol.ex:134: Postgrex.Protocol.message/3
              (postgrex) lib/postgrex/connection.ex:417: Postgrex.Connection.new_data/2
              (postgrex) lib/postgrex/connection.ex:292: Postgrex.Connection.handle_info/2
```

**Comment by josevalim** [comment]
Please check the README. We don't supporting all OIDs out of the box but you can write your own extensions to serialize them in the way that makes most sense to you: https://github.com/ericmj/postgrex#extensions

**Comment by yoavlt** [comment]
@josevalim Sorry, I missed it. Thanks!

**Comment by josevalim** [comment]
Glad to help!
