### ISSUE TITLE
Compile error on production env

### ISSUE THREAD

**Issue by victorlcampos** [ericmj/postgrex#131]
Hi guys,
When I try push to heroku I'm get this error:

```
== Compilation error on file lib/postgrex/connection.ex ==
remote: ** (CompileError) lib/postgrex/connection.ex:207: Postgrex.Connection.__struct__/0 is undefined, cannot expand struct Postgrex.Connection
remote:     (elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4
remote:     (stdlib) lists.erl:1353: :lists.mapfoldl/3
remote:     (stdlib) lists.erl:1354: :lists.mapfoldl/3
```

**Comment by josevalim** [comment]
Closing in favor of https://github.com/phoenixframework/phoenix/issues/1426. Please avoid opening multiple issues. :)

**Comment by victorlcampos** [comment]
Sry,
When I opened this, I thinked that the problem was on postgrex, because I had problems to compile on my local machine.

After I remove _build it's worked local then I open a ticket on phoenix. Sry for did not close this one.

**Comment by josevalim** [comment]
I see. No problem then :D
