### ISSUE TITLE
Nesting hstore

### ISSUE THREAD

**Issue by stevegraham** [ericmj/postgrex#133]
Apparently since 9.4 PG supports nesting hstore and also arrays. What would it take to add this to Postgrex? (I've already had a go but didn't get very far 😞)

**Comment by ericmj** [comment]
I can't seem to find any references to nested hstore in the official docs. This page http://www.postgresql.org/docs/9.4/static/hstore.html says "keys and values are simply text strings".

There seem to be libraries for nested hstore in ORMs such as ActiveRecord, but this is a fake nesting. The nested hstore is stored as a string and doesn't get any of the benefits of a native postgres type such as indexing or function/operator support.

If there is no real support for it in postgres I don't think it should be supported in the driver either, something similar to the ActiveRecord library could be implemented with Ecto types though.

**Comment by stevegraham** [comment]
Did this not make it into 9.4? http://sarahbranon.com/post/70117417009/improved-hstore-the-h-is-for-hooray

**Comment by ericmj** [comment]
If it did make it in I think should have been mentioned in the documentation. Please take a look because I might have missed it.

**Comment by stevegraham** [comment]
I agree it's unclear from the documentation and it's beyond my level of PG expertise to find out. I'm going to close this issue for now. Do you recommend JSON if nesting is a requirement? What is Postgrex's support like at this point?

**Comment by stevegraham** [comment]
After writing the above I discovered that Ecto has a map type corresponding to jsonb, which addresses all the shortcomings of hstore. I found it by chance reading through the Ecto docs looking for something else. Leaving this comment as a note for people coming across this issue in the future with similar requirements.
