### ISSUE TITLE
Better error message on constraint violation

### ISSUE THREAD

**Issue by rranelli** [ericmj/postgrex#134]
It is quite frequent that I get error messages like this:

```
** (Postgrex.Error) ERROR (not_null_violation): null value in column "position_id" violates not-null constraint
```

Since I have a rather complicated schema where more than one table has a column named "position_id", I end up spending some time hunting to discover where exactly the constraint is being violated.

Would it be feasible to add the table name to the error message? Something in the lines of

```
** (Posgrex.Error) ERROR (not_null_violation): null value in column "position_id" of table "mytable" violates not-null constraint.
```

If this is not too hard to implement I would be happy to try sending a PR.

Also, thanks for the great project & effort ! ;D

**Comment by fishcakez** [comment]
If you rescue the exception or use `Postgrex.Connection.query/4`, the exception contains all the relevant data about the error, including the table in this case.

Hopefully this snippet will be enough of a clue of what you want:
```elixir
%Postgrex.Error{postgres: %{table: table}} = exception
```

**Comment by josevalim** [comment]
Maybe we should include the postgres metadata in the error reports?

**Comment by rranelli** [comment]
@fishcakez Nice! That is way easier than what I've been doing :) thanks

@josevalim that might be a good solution. I will take a look in the code and maybe come up with something

**Comment by fishcakez** [comment]
In the map in the containing `table` in the snippet above, sometimes there is a `:detail` key. This can provide much more (useful) information. We should consider appending this to the message if it exists. I am unsure if it will help with this particular case though.

**Comment by josevalim** [comment]
Maybe we should get some of those keys and include in the report. table, detail, what else?

**Comment by fishcakez** [comment]
Here is the data we can get: http://www.postgresql.org/docs/9.4/static/protocol-error-fields.html

**Comment by fishcakez** [comment]
From memory hint and schema are the only other fields not usually included in the message.
