### ISSUE TITLE
Add `connection_id` to Postgrex.Result and Postgrex.Error

### ISSUE THREAD

**Issue by fishcakez** [ericmj/postgrex#137]
We will need a way to pass a connection id from Postgrex to Ecto for logging as the connection pid is no longer a good identifier. It is reused and an implementation detail of DBConnection. This may be useful for other loggers too.

@msch can you handle this?

**Comment by fishcakez** [comment]
We may need to look at a different solution because passing the result of a transaction callback to the log in DBConnection is very complicated code and requires special paths for logging which I would prefer not to do :(. it might be we have to go for a call, similar to how parameters work, to get metadata about a connection. There is an issue tracking this in DBConnection and I will open an issue here once DBConnection has the required mechanism.

**Comment by MSch** [comment]
I actually wanted to file another enhancement request, having the option of doing a call, similar to the `parameters` 'call', that returns the connection id would be helpful for my use case (figuring out the pid of a transaction so I can cancel it)

**Comment by fishcakez** [comment]
Could we have a `metadata/1` that returns a keyword of metadata designed to be passed directly to Logger but can be used for other things. For example we could have `:pg_backend_pid`, `:pg_backend_key`, `:pg_host`, `:pg_user`, `:pg_database` and `pg_connection_pid` in postgrex. In mysql there might  be `:mysql_connection_id`.

In Ecto we would need a way to identify logs in the same transaction. We can achieve this by adding `:conn_ref` to `DBConnection.LogEntry` and a similar field in `Ecto.LogEntry`, which is a reference per checkout from the pool and already part of DBConnection.

Thoughts? I am unsure how this would play in with future plans in Ecto @josevalim?

**Comment by fishcakez** [comment]
Using the result based approach is added in #142.

@MSch if you need the `call` version for `connection_id` you'll need to open an issue
