### ISSUE TITLE
Add function to retrieve current connection_id

### ISSUE THREAD

**Issue by MSch** [ericmj/postgrex#143]
Enhancement request follow up from https://github.com/ericmj/postgrex/issues/137#issuecomment-170148690

I'd like to be able to do a `call`, similar to the parameters 'call', that returns the `connection_id`. I'd use this from within Ecto, so my approach would be to get the Postgres/DBConnection pid as I do right now (by looking into the pdict) and then `call`ing e.g. `Postgrex.Connection.connection_id(pid)`.

Is this something that you'd accept inside Postgrex? How would it work with `DBConnection`/`Ecto`? Does that imply that there needs to be a `DBConnection.connection_id` function as well?

**Comment by josevalim** [comment]
Not sure I understand the question but in Ecto 2.0, you will have access to the Postgrex.Result or Error inside the LogEntry which will give you access to the connection_pid.

**Comment by MSch** [comment]
I'd like to be able to retrieve the `connection_id` inside an Ecto transaction function without having to do a roundtrip to Postgres. My approach would be to get the `connection_pid` from Ecto, then `call` it to get the `connection_id`.

**Comment by fishcakez** [comment]
Would it better to provide a `status` call (similar to :sys.get_status) that returns connection parameters, backend_pid/key and maybe other details as a map? `connection_id` is very specific and so not easy to extend or make generic, I don't think we would want to expose that through Ecto.

**Comment by MSch** [comment]
That would work fine for me, I would have probably used `:sys.get_status` as a workaround otherwise anyhow. I could also see something like `DBConnection.info`, similar to `Process.info`.

**Comment by fishcakez** [comment]
:sys.get_status wouldn't be safe because the pid could have a new connection.

**Comment by ericmj** [comment]
What's the status of this? Is it still needed?

**Comment by fishcakez** [comment]
If one is being naughty and abusing the undocumented `pdict` entry for Ecto 2.0, then it is not a leap to abuse the undocumented DBConnection `pdict` entry that it points to, and from there the Postgrex.Protocol struct is available that contains the `connection_id`. I think we can close this unless someone can propose a fully documented suggestion.
