### ISSUE TITLE
Move Postgrex.Connection to Postgrex

### ISSUE THREAD

**Issue by fishcakez** [ericmj/postgrex#146]
There isn't really a need for the name spacing in this way and there is very little code in Postgrex.Connection. I think @ericmj mentioned doing this for convenience.

**Comment by josevalim** [comment]
Can we do this for v0.11? Just move everything from Postgrex.Connection -> Postgrex?

**Comment by ericmj** [comment]
Yeah, lets bundle it with 0.11. Then the next release can be 1.0 hopefully.

**Comment by fishcakez** [comment]
Except for this, documenting the logging options and a new db_connection release what else is blocking 0.11?

**Comment by ericmj** [comment]
You tell me :). Nothing more is blocking I think.

**Comment by josevalim** [comment]
I am working on this.
