### ISSUE TITLE
Only describe when preparing an already prepared statement

### ISSUE THREAD

**Issue by fishcakez** [ericmj/postgrex#150]
When preparing a query that already exists on the connection an error occurs. Instead we should only describe the query. See: https://travis-ci.org/elixir-lang/ecto/jobs/102873680#L642

This issues blocks `0.11.0`

**Comment by fishcakez** [comment]
The current behaviour for preparing queries is not quite right, as seen by the failing tests.

Currently we always prepare a query when asked to prepare. However if a query with the same name is already prepared on the connection this causes an error. Therefore we should only describe an identical query that already exists on the connection when asked to prepare. However what should we do if a query with the same name but different statement is prepared? Let it fail or close the previous query and prepare the new one? Perhaps this should be configurable?

**Comment by josevalim** [comment]
> However what should we do if a query with the same name but different statement is prepared?

Doesn't this mean the name is wrong? Who is generating the names?

**Comment by fishcakez** [comment]
> Doesn't this mean the name is wrong? Who is generating the names?

Yes it almost certainly does. However in Ecto we need to use a hash for naming I think.

**Comment by josevalim** [comment]
So it sounds like this should be good to close. Can't we use unique_integer or make_ref or something for building the names? We store them in Ecto's ETS and we should be golden.

**Comment by fishcakez** [comment]
> Can't we use unique_integer or make_ref or something for building the names?

Ah yes, for some reason I thought we had to hash the SQL in Ecto but we can use a combination of `unique_integer`, `insert_new` and `update_element` to ensure we only ever create one unique name per cache key.

**Comment by fishcakez** [comment]
> one unique name per cache key.

So we will return error on name reuse?

**Comment by josevalim** [comment]
I think so. Specially if that implies client error.
