### ISSUE TITLE
Error tcp connect: non-existing domain - :nxdomain

### ISSUE THREAD

**Issue by overallduka** [ericmj/postgrex#164]
Hello, im using Mac OSX mavericks and im trying to run an phoenix application using postgrex adapter.
Already search about similar errors but cant find anything anyone have some idea ?

>    
 (recipe_book) web/router.ex:1: RecipeBook.Router.do_call/2
[error] Postgrex.Protocol (#PID<0.344.0>) failed to connect: ** (Postgrex.Error) tcp connect: non-existing domain - :nxdomain
[error] Postgrex.Protocol (#PID<0.344.0>) failed to connect: ** (Postgrex.Error) tcp connect: non-existing domain - :nxdomain
[error] Postgrex.Protocol (#PID<0.344.0>) failed to connect: ** (Postgrex.Error) tcp connect: non-existing domain - :nxdomain
[error] Postgrex.Protocol (#PID<0.344.0>) failed to connect: ** (Postgrex.Error) tcp connect: non-existing domain - :nxdomain
[error] Postgrex.Protocol (#PID<0.344.0>) failed to connect: ** (Postgrex.Error) tcp connect: non-existing domain - :nxdomain
[error] Postgrex.Protocol (#PID<0.344.0>) failed to connect: ** (Postgrex.Error) tcp connect: non-existing domain - :nxdomain
[error] Postgrex.Protocol (#PID<0.344.0>) failed to connect: ** (Postgrex.Error) tcp connect: non-existing domain - :nxdomain
[error] Postgrex.Protocol (#PID<0.344.0>) failed to connect: ** (Postgrex.Error) tcp connect: non-existing domain - :nxdomain
[error] Postgrex.Protocol (#PID<0.344.0>) failed to connect: ** (Postgrex.Error) tcp connect: non-existing domain - :nxdomain
[error] Postgrex.Protocol (#PID<0.344.0>) failed to connect: ** (Postgrex.Error) tcp connect: non-existing domain - :nxdomain

**Comment by josevalim** [comment]
Can you please post your repository configuration from `config/dev.exs`?

**Comment by overallduka** [comment]
Oh, i could fix 2 minutes ago, i add:
`localhost     127.0.0.1 ` in my etc/hosts and restart my mac.

Thanks a lot by the answer, stop now from watching an keynote of you talking about Phoenix, big fan =D.
