### ISSUE TITLE
Consider calling :binary.copy on binaries matched out of received tcp data

### ISSUE THREAD

**Issue by ericmj** [ericmj/postgrex#167]
A user on IRC had an issue where small binaries referenced received tcp data causing all tcp data received from the database to be held in memory. Calling `:binary.copy/1` on the binaries reduced binary memory usage from several gbs to 100mb.

I think we should call `:binary.copy/1` on all binaries matched out of the tcp data.

This also applies to mariex which the user was using.

/cc @josevalim @fishcakez @liveforeverx

**Comment by maxim** [comment]
I'm that user, AMA.

**Comment by fishcakez** [comment]
I am not sure about doing this by default because it creates extra copies/garbage collection when the binaries are not long lived/shared. I think there is a disclaimer about not using `:binary.copy/2` unless required in the efficiency guide or somewhere in the docs. It is one of those situations where it is possible to do it by hand if it isn't on by default but cant be undone if done by default.

I think we do copy the binaries that are long lived/put in ETS at the moment in postgrex, or at least there is a TODO.

**Comment by fishcakez** [comment]
One thing to note is that with postgrex (and in near future mariaex) the connection process never touches the binaries from a query. This means we can't get into the situation where the connection process is sitting idle and not gc'ing a big binary.

**Comment by josevalim** [comment]
Ah, good call. @maxim was probably using the version of mariaex without db_connection. Closing this then!

**Comment by maxim** [comment]
Yes, I've used mariaex 0.5.0 since that's what I'm locked into from with phoenix_ecto 2.0.1.

**Comment by fishcakez** [comment]
@maxim issue would still occur with db_connection because the binaries used would still point to larger binaries.

**Comment by ericmj** [comment]
As @fishcakez said this issue will still occur even if the connection process does not hold on to the binaries.

> I am not sure about doing this by default because it creates extra copies/garbage collection when the binaries are not long lived/shared.

It shouldn't create extra garbage because the larger binary can be reclaimed much quicker, especially now that the connection process wont hold on to it. I think we should do this by default because the dangerousness of not doing it doesn't outweigh the performance benefit of copying some extra binaries. If someone wants lolspeed (and they can actually show that copying is slower) we can add a switch that disables the safe copying.

**Comment by maxim** [comment]
I agree with @ericmj because runaway RAM is never right, and ETS cache is not an obscure use-case.

**Comment by liveforeverx** [comment]
I have read about binary:copy several times in erlang docs && guide(knows about, but don't run in the same issues somewhere until now). 

http://erlang.org/doc/man/binary.html#copy-2 
> "Only in special cases, when small parts reference large binaries and the large binaries are no longer used in any process, deliberate copying might be a good idea." 

I think, it is exactly our use case, and we should copy default.

**Comment by fishcakez** [comment]
> http://erlang.org/doc/man/binary.html#copy-2
> 
>     "Only in special cases, when small parts reference large binaries and the large binaries are no longer used in any process, deliberate copying might be a good idea."
> 
> I think, it is exactly our use case, and we should copy by default.

For me I take away the opposite opinion and it should be up to someone to explicitly copy if they face the situation as it is warning against always copying unless there is an issue. I feel like we are trying to outsmart the VM.

Using ETS is not obscure but I think facing the situation where a massive binary is accumulated and only a small part of it kept around in ETS is a rare case, certainly not that faced for 80% of cases. Presumably this is happening when there are a couple of small text/uuids and a lot of numbers in a row? @maxim?

From memory I think `erlang:binary_to_term` does a copy for binaries so there's that. Perhaps we could run tests to show even when it's not beneficial to copy it does not result in significantly more memory usage?

**Comment by maxim** [comment]
> Presumably this is happening when there are a couple of small text/uuids and a lot of numbers in a row?

@fishcakez Not a lot of numbers. Here's the SQL query:

```sql
SELECT b0.`id`, b0.`name`, b0.`entry`, a1.`id`, a1.`username` FROM `things`
  AS b0 INNER JOIN `accounts` AS a1 ON a1.`id` = b0.`account_id`
  WHERE (b0.`id` > ?) ORDER BY b0.`id` LIMIT ? [0, 1000] OK query=32.3ms
```

Data types are

  * id - integer (all ids in the query)
  * name - string (<20 chars long)
  * entry - varbinary (13 bytes)
  * username - string (<20 chars long)

As you see, the query has a `JOIN` in it, and is fetched repeatedly in batches of 1000s. Before calling `:binary.copy`, each batch was adding 20MB to RAM, and wasn't releasing it. There are 3 integer fields and 3 binary fields, but `entry` is being converted into a list on load, using a custom Ecto type.

**Comment by fishcakez** [comment]
Well a couple of small binaries and the rest are not binaries in ETS. If that entry is converted to a list of bytes thats 2 small binaries and 16 numbers :trollface:. Though really this seems like an obvious case for `:binary.copy/2` that unfortunately is not obvious until you know about it, so if we don't add an automatic copy we would definitely need to add documentation.

**Comment by maxim** [comment]
Heh, I didn't actually specify what's going into ETS, just what's being loaded from SQL. Each element in the list is an integer 0,1, or 2. The ETS then receives 2 tuples (key and value), key containing 3 integers, and value containing 2 strings (the same ones as in the query), and 3 integers.

```elixir
# this is the ETS term structure, wrapping strings in binary.copy made the problem go away
{{int, int, int}, {:binary.copy(name), int, int, int, :binary.copy(username)}}
```

And yes, the `:binary.copy` trick is completely obscure. I think it's a bug in the db driver, but I don't know how best to fix it. Perhaps do a size check, and just always copy if result set is larger than threshold?

**Comment by fishcakez** [comment]
> Perhaps do a size check, and just always copy if result set is larger than threshold?

The problem with that is if a row is decoded to a list of binaries then each binary might be small compared to the row but reusing the row binary is very efficient.

**Comment by josevalim** [comment]
Let's always copy. It is the correct thing to do.

On Thursday, February 18, 2016, James Fish <notifications@github.com> wrote:

> Perhaps do a size check, and just always copy if result set is larger than
> threshold?
>
> The problem with that is if a row is decoded to a list of binaries then
> each binary might be small compared to the row but reusing the row binary
> is very efficient.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ericmj/postgrex/issues/167#issuecomment-185467930>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by fishcakez** [comment]
> Let's always copy. It is the correct thing to do.

If it is the correct thing to do, that implies we should be using copies for things like json decoding, in e.g. Poison?

**Comment by josevalim** [comment]
It is the correct thing to do *in this case, based on this discussion*. :) I was too terse, sorry!

**Comment by fishcakez** [comment]
I think I was too terse in fact! How should we handle json and hstore in postgrex?

**Comment by josevalim** [comment]
Ah.... good question. No idea. :( Should we wait until somebody has a use case? Wouldn't they already hold a smaller binary anyway because what they received was already copied? Does Poison copy?

**Comment by ericmj** [comment]
For json we should copy before passing it to the json decoder and let the json library handle it. Poison does not copy currently.

Since we decode hstore ourselves we should copy binaries after decoding.

Alternatively, since this seems to be an "issue" with every decoder library maybe we should just leave as-is and educate users about it?

**Comment by maxim** [comment]
> maybe we should just leave as-is and educate users about it?

Hard to imagine what it would read like. "Internally drivers/decoders might parse big blobs, and if you keep those terms around, blobs will stay in RAM with them, be mindful of this leaky implementation detail." Official low-level db drivers shouldn't be the place where you chase/discover memory leaks.

**Comment by ericmj** [comment]
> Official low-level db drivers shouldn't be the place where users chase/discover memory leaks.

To be fair, the leak is in your application. This discussion is about if it's worth it to lower the general performance of the driver to avoid these user errors.

**Comment by maxim** [comment]
I'm surprised it's seen that way. I guess we'll disagree on that.

**Comment by josevalim** [comment]
@ericmj I think we should copy. For example, Ecto 2.0 introduces parallel preloading, which means copying via Task.async+await. It would be PITA to traverse the data structures and dump everything. I wish we had an option to `send` that would copy binaries instead of sending references. :S Or at least a function that would do a "deep copy" so we didn't have to traverse the whole structure ourselves.

**Comment by josevalim** [comment]
Btw, if someone would like to pick this up, it would be really appreciated.

**Comment by ericmj** [comment]
I'm still not sure if we should do this. We need benchmarks first either way.

**Comment by josevalim** [comment]
I think this is the correct thing to do, with or without numbers, otherwise, as I said, things like parallel preloading in Ecto would totally leak binaries. I think we should copy by default, if someone wants raw speed, then they can disable this behaviour.

**Comment by ericmj** [comment]
Agreed. This is up for grabs. The default should be to copy but we need an option to disable it.
