### ISSUE TITLE
No extension found for oid '57317'

### ISSUE THREAD

**Issue by cblavier** [ericmj/postgrex#168]
Hey, 

Using Postgrex 0.11.1 (along with Postgres 9.5 / PostGIS 2.2), I get an `no extension found for oid '57317'` error when using ST_Extent function (which returns something like that: `BOX(-4.71665 41.48708,9.51243 51.05328)`)

Thanks for your help

**Comment by ericmj** [comment]
An extension has to be created for the postgis types. Check the docs http://hexdocs.pm/postgrex/Postgrex.Extension.html and here for examples of extensions https://github.com/ericmj/postgrex/tree/master/lib/postgrex/extensions.

**Comment by cblavier** [comment]
Thanks, just wrote this extension, it seems to be working properly.
https://gist.github.com/cblavier/96b6ed9136400f14b1bd

**Comment by kansi** [comment]
Hey,
@cblavier looking at your extension, I tried to write my own
```elixir
defmodule Postgrex.Extensions.GeoPoint do
  alias Postgrex.TypeInfo
  alias Postgrex.Point
  @behaviour Postgrex.Extension

  def init(_parameters, _opts) do :ok end

  def matching(_) do [type: "geometry"] end

  def format(_) do :text end

  def encode(%TypeInfo{type: "geometry"}, %Point{x: x, y: y}, _state, _library) do
    "POINT(#{x} #{y})"
  end
  def encode(type_info, value, _, _) do
    raise ArgumentError,
      Postgrex.Utils.encode_msg(type_info, value, "an array of 2 Postgrex.Point")
  end

  def decode(%TypeInfo{type: "geometry"}, point, _state, _library) do
    parse_point(point)
  end
  defp parse_point(point) do
    [lat, lng] =
      point
      |> String.split(["(", " ", ")"])
      |> Enum.slice(1..-2)

    %Point{x: Float.parse(lat), y: Float.parse(lng)}
  end
end

```
The I tried using it as follows but it crashes
```elixir
{:ok, pid} = Postgrex.start_link(extensions: [{Postgrex.Extensions.GeoPoint, library: {}}], database: "mydb")
Postgrex.query!(pid, "SELECT location_latlng from events", [])
```
this is because `location_latlng` is of form `"0101000020E61000009F56834A26CC3A40000008A45AF55240"` rather than being of the form `POINT(26.7974592753077 75.8336572721601)`
But if I use the following query to get the `POINT` representation the extension is not used
```elixir
iex(4)> Postgrex.query!(pid, "SELECT ST_AsText(location_latlng) from events", [])
%Postgrex.Result{columns: ["st_astext"], command: :select, connection_id: 27516,
 num_rows: 1, rows: [["POINT(26.7974592753077 75.8336572721601)"]]}
```

Also I am wondering if I can use this from `Ecto` as I am using Phoenix.
