### ISSUE TITLE
mix compile failed on v0.11.0

### ISSUE THREAD

**Issue by jeandavid** [ericmj/postgrex#170]
Hi Eric, 

Updating elixir to 1.2 (from 1.0), phoenix to 1.1.4 (from 1.0.3), I also updated :postgrex to 0.11.0. 
When I run mix deps.get, it fails on postgrex:

`(CompileError) lib/postgrex/protocol.ex:61: Postgrex.Protocol.__struct__/0 is undefined, cannot expand struct Postgrex.Protocol`
`(elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4`
Any help? 

Thanks!!

**Comment by josevalim** [comment]
@jeandavid try nuking `_build` and let us know if it works.

**Comment by jeandavid** [comment]
@josevalim could you please be more explicit? Thank you:)

**Comment by josevalim** [comment]
Sure! In your application, there is a `_build` and `deps` directory. Please fully remove both of them and then run `mix deps.get` and `mix test` and let us know if it works.

**Comment by jeandavid** [comment]
Great it compiled!
Thanks a lot @josevalim !!

**Comment by jeandavid** [comment]
@josevalim Now that I am trying to update the production server on heroku, I get the same issue. I am not sure that I can manually delete a folder in an heroku app. 
Would you know how to push changes to the production repo on heroku? Thanks!!!

**Comment by josevalim** [comment]
Set the "always_rebuild=true" on your heroku deployment configuration:

https://github.com/HashNuke/heroku-buildpack-elixir#configuration

**Comment by divmgl** [comment]
Still running into this issue with `0.11.1` after removing `_build` and `deps`.

**Comment by divmgl** [comment]
Disregard, running `mix` seems to have fixed it.
