### ISSUE TITLE
execute query in chunks

### ISSUE THREAD

**Issue by thenrio** [ericmj/postgrex#175]
say, fetch 400,000 rows by chunks of 1000 

there are two goals

* improved capability
when rows do not fit in memory, pulling then writing all chunks SHOULD enable to write all rows

* increased performance
`total_response_time( chunk_size )` MAY look like a U curve

( see elixir-lang/ecto#493, and also #7 that enables this feature )

**Comment by fishcakez** [comment]
Added in 7e6822d7d1d241f9fd8388a3c022cf8612002db4
