### ISSUE TITLE
(ArgumentError) no extension found for oid `19`

### ISSUE THREAD

**Issue by andrewtimberlake** [ericmj/postgrex#178]
I’m trying to run the following query through Ecto both as a built up query and as a raw SQL query, both give me the above error.

The query is,
```sql
select
    t.relname as table_name,
    i.relname as index_name,
    a.attname as column_name
from
    pg_class t
    join pg_index ix on t.oid = ix.indrelid
    join pg_class i on ix.indexrelid = i.oid
    join pg_attribute a on a.attrelid = t.oid
where
    a.attnum = ANY(ix.indkey)
    and t.relkind = 'r'
    and ix.indisunique
    and a.attname != 'id'
    and t.relname = 'users'
order by
    t.relname,
    i.relname;
```

**Comment by ericmj** [comment]
We need to add support for the `name` type. As a workaround you can cast the selected columns to `text`.

**Comment by ericmj** [comment]
A PR would be appreciated.

**Comment by vietord** [comment]
Ran into the same issue. For the curious my use case was validating that a particular set of extensions existed before running a migration, and the pg_available_extensions name column is of the name type. 

#216
