### ISSUE TITLE
How to specify PG version 9.5.0

### ISSUE THREAD

**Issue by madshargreave** [ericmj/postgrex#182]
I am currently having trouble with a version mismatch when running `pg_dump` on my docker hosted app

It complains the server is version `9.5.0`, while the client is `9.4.5`.

I am not sure if this is the correct part of the stack to specify the client version, if so, how can I change it so it matches?

**Comment by josevalim** [comment]
@madshargreave I don't think this is related to postgrex at all. pg_dump does not go through postgrex.

**Comment by ericmj** [comment]
You likely need to update the postgresql client package on your system.
