### ISSUE TITLE
Support ltree column type

### ISSUE THREAD

**Issue by jamesvl** [ericmj/postgrex#184]
I'd like to add support for the `ltree` column type.

The test in `query_test.exs` would be something like:

    test "decode ltree", context do
      assert [["1.2.3"]] = query("SELECT '1.2.3'::ltree", [])
      assert [[true]] = query("SELECT '1.2'::ltree @> '1.2.3'::ltree", [])
    end

And the `test_helper.exs` script needs this added to its definition of `sql` (otherwise the OID for ltree types are never known during the test run):

    CREATE EXTENSION IF NOT EXISTS ltree;

I've tried my best to create the actual extension, but it seems Postgres has no support for sending ltree data in its binary protocol - it must be text. So I'm not sure how to proceed.

Casting ltree columns to `::TEXT` is not a viable option, because then I can't use query operators specific to ltrees (like `col1 @> col2`).

The Postgres error struct returned is

    %Postgrex.Error{connection_id: 4750, message: nil,
            postgres: %{code: :undefined_function, file: "lsyscache.c", line: "2620",
              message: "no binary output function available for type ltree", pg_code: "42883", routine: "getTypeBinaryOutputInfo",
              severity: "ERROR"}}

I believe the relevant Postgres source is probably [this function](http://doxygen.postgresql.org/ltree__io_8c.html#a32fb93e20905d0baa8e5361929eacb68).

**Comment by fishcakez** [comment]
Postgrex supports binary and text encoding. The `Postgrex.Extension` behaviour docs should point the way, especially the `:format/1` callback for choosing the encoding type. You aren't the first person to stumble on extensions for text encoding, is there somewhere we (incorrectly) suggest we don't support text encoding?

**Comment by jamesvl** [comment]
Lack of examples, perhaps? The first thing I did was try to see if other extensions used the `:text` format.

Docs are not super clear to me; then again, I've only begun my deep dive into Elixir. I'll gladly submit PRs if I think I can add some clarity to them.

And I do have

      def format(_), do: :text

in my extension; when that still wasn't working I decided to post here.

**Comment by fishcakez** [comment]
What do you try for `matching/1`? For text format you would want something
like `[output: "type_out"]` or `[output: "typeout"]`. To find the correct
send or output matching value you can do the following:

* Try a query like "SELECT foo::type" without a matching extension and get
an oid not found error.
* Lookup the encoding of send and output with "SELECT
typsend::text,typoutput::text FROM pg_type where oid=$1" where $1 is the
oid from the error, you may also wish to lookup typreceive or typeinput to
see how to encode, though postgrex will add the extension for encoding and
decoding if any of type, send, receive, output or input match and it will
just be the reverse operation. send and receive are for binary, and output
and input for text. send/output is how postgres sends the terms and
receive/input is how postgres receives the terms.
* Implement `matching/1` using `send` or `output` depending on whether
format is `:binary` or `:text`. See Postgrex.Extensions.Void for an example
of this.


If using the text format and not doing any encoding/decoding of the text
you can do the following without having to look up type encoding
information:

```
defmodule MyExtensions.Text do
  @behaviour Postgrex.Extension

  def init(_, _), do: nil

  def matching(_), do: [type: "my_type1", type: "my_type2"]

  def format(_), do: :text

  def encode(_, text, _, _) when is_binary(text), do: text

  def decode(_, text, _, _), do: text
end
```

**Comment by jamesvl** [comment]
Ah! I got it working now.

It really was just my inexperience with Elixir, knowing how to properly hook into the Postgrex `@behaviour`, and not seeing another text extension to work (ahem, copy/paste) from. Was actually pretty easy.

Is there anywhere in the docs I can look to how to include this extension into postgrex? Should I create a pull request for this to be added?

**Comment by fishcakez** [comment]
I will differ to @ericmj whether to add the extension for `ltree`. If you want to do a PR it should be a case of adding the `Postgrex.Extensions.LTree` module with a `decode_binary` option (see `Postgrex.Extensions.Raw`), adding the module to the list of default extensions in `Postgrex.Utils` and adding an encode/decode test in `test/query_test.exs`.

A recent extension PR: https://github.com/ericmj/postgrex/pull/161.

**Comment by ericmj** [comment]
If ltree ships with postgresql we can add it but if it only supports the text format I am hesitant since it won't compose with other data structures.

**Comment by jamesvl** [comment]
Thanks all for the help with this.

Agreed that there's not much point in including the ltree extension if it's just text and not binary. I'm going to see if I can understand if / what the Postgres binary format is for ltree data and will try to write the extension (using PR #161 as an example) for your review.

Two things that may help in the mean time:
- where the docs say things like `Postgrex uses the binary protocol, not the text protocol`, I was led to assume that text extensions were not possible at all. You may want to add something that clarifies, "Postgres uses the binary protocol by default, but can fall back to the text protocol for extensions that require it. This may cause issues since it won't compose well with other data structures."
- if I wanted to use a text-based extension (until I figure out the binary version), would someone be willing to document how to do so? I assume I'd have to fork the Postgrex source, add my extension, and use my version in my mix dependencies, but would love to learn if there's a more elegant way to do it.

**Comment by fishcakez** [comment]
You don't need to fork postgrex, simply: 
* Create extension module, e.g. `MyApp.Extensions.LTree`, inside your own application
* Add `[extensions: {MyApp.Extensions.LTree, opts}]` to `Postgrex.start_link/1` options, where `opts` is any term passed to the `init` callback.

**Comment by fishcakez** [comment]
That should be `[extensions: [{MyApp.Extensons.Tree, opts}]]`

**Comment by jamesvl** [comment]
Thanks for the direction - I'll do that!

I did just write up a binary version that matches what's defined in the Postgres `ltree.h` source code. Unfortunately, I believe Postgres will only send it as string, as it gives back

```
 %Postgrex.Error{connection_id: 1202, message: nil,
            postgres: %{code: :undefined_function, file: "lsyscache.c", line: "2620",
              message: "no binary output function available for type ltree", pg_code: "42883", routine: "getTypeBinaryOutputInfo",
              severity: "ERROR"}}
```

Looks like it's string-only for this data type.

**Comment by denispeplin** [comment]
Have anybody got working extension yet? I expected it'll work just like string from Elixir, and I was surprised it doesn't work at all, and anybody who want to use ltree should spend God know how many hours writting it (I did't even find an article about writing Posgrex extensions).

**Comment by fishcakez** [comment]
@denispeplin it is unfortunate it is a struggle. It should be very easy to do but we have clearly not communicated how to do it well enough. If you post your code I can help you.

**Comment by fishcakez** [comment]
@denispeplin I have added ltree as an example in the docs: https://github.com/elixir-ecto/postgrex/commit/a417a6525280654ab33b6502eee7008bf8ed16ad

**Comment by denispeplin** [comment]
@fishcakez, thank you for example, it works!
I've just run example from README, and it works now.

Before:
```elixir
{:ok, pid} = Postgrex.start_link(hostname: "localhost", username: "postgres", password: "postgres", database: "my_database")
{:ok, #PID<0.217.0>}
iex(6)> Postgrex.query!(pid, "SELECT path FROM messages", [])
** (ArgumentError) no extension found for oid `1305491`: %Postgrex.TypeInfo{array_elem: 0, base_type: 0, comp_elems: [], input: "ltree_in", oid: 1305491, output: "ltree_out", rece
ive: "-", send: "-", type: "ltree"}
```

After:
```elixir
{:ok, pid} = Postgrex.start_link(hostname: "localhost", username: "postgres", password: "postgres", database: "my_database", extensions: [{MyApp.LTree, :copy}])
{:ok, #PID<0.213.0>}
(search)`SELE': Postgrex.query!(pid, "SELECT path FROM messages", [])
%Postgrex.Result{columns: ["text"], command: :select, connection_id: 2279,
 num_rows: 3, rows: [["path"], ["path.path"], ["path.path.path"]]}
```

And I guessed that for Ecto I should add `extensions` right to its config, and it works now! (this is maybe what is missing from documentation, but from `Ecto` documentation).

But I would vote for fallback to binary for every unsupported format to avoid confusion.

**Comment by jamesvl** [comment]
And just in case anyone finds this issue and is trying to get this working with Ecto 2.1+ / Postgrex 0.13+, the docs are crystal clear:

* https://hexdocs.pm/postgrex/0.13.0/Postgrex.Extension.html#content
* https://hexdocs.pm/ecto/Ecto.Adapters.Postgres.html

**Comment by lcacciagioni** [comment]
@jamesvl is it possible to also add the lquery example?

**Comment by jamesvl** [comment]
@lcacciagioni Not sure what you mean by lquery example?

If you mean just using the extension, setup a schema and uses the `Ltree` type:

```elixir
  schema "roles" do
    field :title, :string
    field :description, :string
    field :node_path, Ltree
  end
```

Then after that I write custom SQL queries, per the Postgres docs, to make use of the special operators on that column:
```sql
   SELECT id, title
     FROM roles
    WHERE node_path <@ (SELECT node_path FROM roles WHERE id = $1)
      AND id != $1
```

**Comment by cotter** [comment]
I'm having difficulty implementing based on the Ecto 2.1/Postgrex 0.13 samples.

```
defmodule MyApp.LTree do
  @behaviour Postgrex.Extension

  def init(opts) when opts in [:reference, :copy], do: opts
  def matching(_opts), do: [type: "ltree"]
  def format(_opts), do: :text

  def encode(_opts) do
    quote do
      bin when is_binary(bin) ->
        [<<byte_size(bin) :: signed-size(32)>> | bin]
    end
  end

  def decode(:reference) do
    quote do
      <<len::signed-size(32), bin::binary-size(len)>> ->
        bin
    end
  end
  def decode(:copy) do
    quote do
      <<len::signed-size(32), bin::binary-size(len)>> ->
        :binary.copy(bin)
    end
  end
end
```

```
Postgrex.Types.define(MyApp.PostgresTypes,
                      [{MyApp.LTree, :copy}] ++ Ecto.Adapters.Postgres.extensions(),
                      json: Poison)
```

```
config :my_app, MyApp.Repo,
  adapter: Ecto.Adapters.Postgres,
  ...
  types: MyApp.PostgresTypes
```

This fails with the below error. It's balking at `function_exported?(type, :type, 0)`.

```
== Compilation error on file web/models/user.ex ==
** (ArgumentError) invalid or unknown type MyApp.LTree for field :manager_path
    lib/ecto/schema.ex:1727: Ecto.Schema.check_type!/3
    lib/ecto/schema.ex:1431: Ecto.Schema.__field__/4
    ...
```

I thought the Postgrex.Extension would cover that but maybe I'm missing something. Any ideas?
