### ISSUE TITLE
disconnection when retrieving huge JSON column

### ISSUE THREAD

**Issue by sdesbure** [ericmj/postgrex#185]
Hello, I'm working on a server that create a map looking like this:

```
{
  "domains": {
     "amazon.com": "two_domains_one_ip",
     "lemonde.fr": "two_domains_one_ip",
     "virtualskipper.com": "special"
   },
   ips": {
     "4.5.6.7": "two_domains_one_ip"
   }
}
```

I manage to create huge column (32M and 76M of JSON) but I cannot retrieve with postgrex the second one :
`[error] Postgrex.Protocol (#PID<0.344.0>) disconnected: ** (Postgrex.Error) tcp recv: not enough 
memory - :enomem`

I tried to play with socket options (ended with  `socket_options: [recbuf: 16777216, sndbuf: 16777216],`) but it doesn't make it work (the 32M works with far less big buffers).

Any idea to tweak postgrex to make it work?

thanks!

**Comment by ericmj** [comment]
How much free memory do you have on the machine and how memory have postgrex used when you get the error?

**Comment by fishcakez** [comment]
@sdesbure could you included your OS information?

A quick search picked up this old mailing list thread: http://erlang.org/pipermail/erlang-questions/2006-September/022909.html. If this or a similar situation still exists I think we could limit the max recv size.

**Comment by sdesbure** [comment]
Hello,
thanks both of you for trying to solve the issue :)
Here's my answers
@ericmj 
phoenix server started: 
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            15G        2,8G        8,8G        509M        4,0G         11G
Swap:          5,6G          0B        5,6G
```

retrieving the "small" json file:
```
$ curl localhost:4000/api/blacklists/2
(200 OK)  ([info] Sent 200 in 5115ms)
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            15G        3,3G        8,2G        515M        4,0G         11G
Swap:          5,6G          0B        5,6G
```

retrieving the "big" json file:
```
$ curl localhost:4000/api/blacklists/5
(500 ERROR) [info] Sent 500 in 754ms
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            15G        2,9G        8,6G        533M        4,1G         11G
Swap:          5,6G          0B        5,6G
```

@fishcakez 
my OS is debian stretch
postgresql: 9.5+174
iex : Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]
postgrex: 0.11.1

if it can help...

**Comment by ericmj** [comment]
So it seems like an allocation issue in the OS TCP buffers. I think we need to limit the size of the receives we do.

**Comment by sdesbure** [comment]
Hello, the problem is solved!

Thank you :)
