### ISSUE TITLE
Please depend on db_connection "~> 1.0.0-rc" and release a new version

### ISSUE THREAD

**Issue by josevalim** [ericmj/postgrex#201]

**Comment by fishcakez** [comment]
I think #192 would be the only blocker for a `1.0.0-rc.0`, what do you think @ericmj, perhaps we could have a `1.0.0-pre.0`?

**Comment by ericmj** [comment]
Sounds good. It seems #205 could be a breaking change also?

**Comment by fishcakez** [comment]
Yes that too.

**Comment by fishcakez** [comment]
@ericmj since #192 is a backwards compatible addition and calendar hasn't landed in ecto nor Elixir stable, perhaps we could do a release so we can do a new Ecto rc? It need not be `1.0.0-rc.0` if you don't want.

**Comment by ericmj** [comment]
We can cut 1.0.0-rc.0 but that means we would have to release 2.0.0 if we want to change the calendar type defaults. Depending on when elixir 1.3.0 is going to release it might be better to cut a <1.0.0 release with support for the new calendar types but with the current defaults, then release 1.0.0 with the new calendar defaults.

**Comment by fishcakez** [comment]
@ericmj lets go for whatever version you want :smile:

**Comment by josevalim** [comment]
@ericmj it depends on what we want to do. Do we want Postgrex to depend exclusively on Elixir v1.3? If so, then we should release `0.NEXT`. If we want to simply provide calendar types as extensions, then this one can be a 1.0.0-rc.0. I thought you didn't want to depend exclusively on Elixir v1.3. So what are your thoughts?

**Comment by fishcakez** [comment]
Before a release we should change the docs to point to DBConnection for all pooling options because I think we may have got out of sync with defaults and are missing options, like `:log`. I will go through that today.

**Comment by fishcakez** [comment]
> Before a release we should change the docs to point to DBConnection for all pooling options because I think we may have got out of sync with defaults and are missing options, like :log. I will go through that today.

Done
