### ISSUE TITLE
Add tsvector extension

### ISSUE THREAD

**Issue by mspanc** [ericmj/postgrex#204]
Hello,

at the moment attempt tu use postgrex with table that contains tsvector column ends up with the following errors:

```
[debug] BEGIN [] OK query=0.5ms
** (ArgumentError) no extension found for oid `3614`
[debug] ROLLBACK [] OK query=0.5ms
         (postgrex) lib/postgrex/types.ex:298: Postgrex.Types.fetch!/2
         (postgrex) lib/postgrex/types.ex:215: Postgrex.Types.encoder/2
           (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
           (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
         (postgrex) lib/postgrex/query.ex:82: DBConnection.Query.Postgrex.Query.encoders/2
         (postgrex) lib/postgrex/query.ex:43: DBConnection.Query.Postgrex.Query.describe/2
    (db_connection) lib/db_connection.ex:884: DBConnection.describe_execute/5
    (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
```

I can try to implement this but can you give me any guidance before I read whole source code of postgrex?

**Comment by fishcakez** [comment]
An example PR is here: https://github.com/ericmj/postgrex/pull/161

Note that the extensions can be used from your project and need not be part of postgrex.

**Comment by ericmj** [comment]
Please send a PR. If you have any additional questions, feel free to ask them here or in your PR, thank you.
