### ISSUE TITLE
Review `command`, `rows` and `num_rows` in result struct

### ISSUE THREAD

**Issue by fishcakez** [ericmj/postgrex#205]
Now that we have streams we generate result structs without getting a completed message from postgres. This system should be reviewed for consistency and then tested.

When streaming should `num_row`s be the number of the rows returned in the result? When copying from the database we know the running total and include the number matching the row count. However when copying to the database we don't - until the copy stream is closed where we get the number.

When streaming we don't know the command until the end, currently we use `:stream` for streaming rows from the database and `:copy_stream` when stream copying from or to the database. When streaming rows or copying from the database we skip results that have empty rows and can miss the actual command. Should we include results where `rows: []` and `rows: nil` in the stream? The `rows: []` case would be the last result in a stream and include the actual `:command` but no rows.The `rows: nil` case would be a single result for the stream. Currently we ignore both and don't return them. This is inconsistent. We are streaming results and not rows.

**Comment by fishcakez** [comment]
Fixed in https://github.com/ericmj/postgrex/commit/881c9951bc7f76d9ba4aa5fb366b7fe93855095f.

**Comment by ericmj** [comment]
:+1:
