### ISSUE TITLE
Support hstore type

### ISSUE THREAD

**Issue by joshnuss** [ericmj/postgrex#39]
Would be cool if there was encoding/decoding for maps as hstores.

Can open a PR if you'd like.

**Comment by ericmj** [comment]
Yes, please go ahead.

**Comment by robertsosinski** [comment]
Noticed there is already a package on hex that adds hstore support to Postgrex at https://github.com/senecasystems/hstore

Maybe work with the author to merge it in?

**Comment by joshnuss** [comment]
Thanks @robertsosinski!

@tyre @ericmj what do you think about combining the hstore hex project?

**Comment by ericmj** [comment]
That project uses the text format encoding, postgrex uses the more efficient binary format when possible.

**Comment by ericmj** [comment]
Ping?

**Comment by tyre** [comment]
Sorry, I forgot about this one. Would you like me to convert it to binary?

What else would be necessary to merge it in?

**Comment by ericmj** [comment]
Using the binary format should be enough.

**Comment by tyre** [comment]
Got around to doing the conversion. Pretty easy with the extension support built into Postgrex. Great work with that!
