### ISSUE TITLE
Cannot encode date 1999-12-31 properly

### ISSUE THREAD

**Issue by hamiltop** [ericmj/postgrex#44]
With `0.7.0`, `{1999,12,31}` is encoded as `-1` which is later treated as `null`.

It seems to be fixed in master, but from the looks of commit logs it might have been fixed by coincidence.

I opened this issue as just a simple heads up in case this wasn't known.

**Comment by ericmj** [comment]
Do you know which commit fixed it?

**Comment by hamiltop** [comment]
git bisect says b4ea8d548d56e04e836d0fe0a0c61b979c59c8f5 fixed it.

I added a test for it at https://github.com/ericmj/postgrex/pull/45

**Comment by ericmj** [comment]
I guess making NULL handling explicit was a better decision than I knew. Thanks for taking the time and looking into it.
