### ISSUE TITLE
Translate Postgres error codes into atoms

### ISSUE THREAD

**Issue by MSch** [ericmj/postgrex#51]
Would be nice to translate the string codes into atoms, the naming scheme is already perfect: www.postgresql.org/docs/9.4/static/errcodes-appendix.html

https://github.com/postgres/postgres/blob/master/src/backend/utils/errcodes.txt

**Comment by ericmj** [comment]
I agree :+1:

**Comment by ericmj** [comment]
Closed in favor of PR #52.
