### ISSUE TITLE
(ArgumentError) no extension found for oid

### ISSUE THREAD

**Issue by zipme** [ericmj/postgrex#60]
After updating to 0.8.0, I got an error "no extension found for oid" when running a query like Postgrex.Connection.query!(pid, "SELECT xxx FROM subjects", [])

**Comment by ericmj** [comment]
Please include the full error message. Which oid is failing? We've removed automatic text fallback for types we don't handle by default which is probably causing this error.

**Comment by jasonwebster** [comment]
I'm seeing:

```
** (ArgumentError) no extension found for oid `114`
  (postgrex) lib/postgrex/types.ex:285: Postgrex.Types.fetch!/2
  (postgrex) lib/postgrex/types.ex:218: Postgrex.Types.format/2
  (postgrex) lib/postgrex/protocol.ex:279: anonymous fn/2 in Postgrex.Protocol.encode_params/1
  (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
  (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
  (elixir) lib/enum.ex:977: Enum.map/2
  (postgrex) lib/postgrex/protocol.ex:275: Postgrex.Protocol.encode_params/1
  (postgrex) lib/postgrex/protocol.ex:245: Postgrex.Protocol.send_params/2
```
after attempting an insert on a table that has a json column in it.

**Comment by ericmj** [comment]
@jasonwebster oid 114 is json. See the readme for an example json extension.

**Comment by zipme** [comment]
I have a table called 'subjects' which has a `jsonb` column, bellow is the full error message:

```
05:21:16.182 [debug] SELECT s0."id", s0."data" FROM "subjects" AS s0 LIMIT 1 [] (61.8ms)
** 
(ArgumentError) no extension found for oid `3802`
    (postgrex) lib/postgrex/types.ex:285: Postgrex.Types.fetch!/2
    (postgrex) lib/postgrex/types.ex:218: Postgrex.Types.format/2
    (elixir) lib/enum.ex:977: Enum."-map/2-lc$^0/1-0-"/2
    (elixir) lib/enum.ex:977: Enum."-map/2-lc$^0/1-0-"/2
    (postgrex) lib/postgrex/protocol.ex:124: Postgrex.Protocol.message/3
    (postgrex) lib/postgrex/connection.ex:428: Postgrex.Connection.new_data/2
    (postgrex) lib/postgrex/connection.ex:302: Postgrex.Connection.handle_info/2
    (stdlib) gen_server.erl:599: :gen_server.handle_msg/5
```

**Comment by ericmj** [comment]
You fix it the same way. Just change `type: "json"` to `type: "jsonb"`.

**Comment by zipme** [comment]
THANKS! It's working now!

**Comment by cmelgarejo** [comment]
@zipme how do you parse the jsonb format? throw me a bone here :) :meat_on_bone:

**Comment by zipme** [comment]
@cmelgarejo I use the example code in README:

```
defmodule Extensions.JSON do
  alias Postgrex.TypeInfo

  @behaviour Postgrex.Extension
  @json ["json", "jsonb"]

  def init(_parameters, opts),
    do: Keyword.fetch!(opts, :library)

  def matching(_library),
    do: [type: "json", type: "jsonb"]

  def format(_library),
    do: :binary

  def encode(%TypeInfo{type: type}, map, _state, library) when type in @json,
    do: library.encode!(map)

  def decode(%TypeInfo{type: type}, json, _state, library) when type in @json,
    do: library.decode!(json)
end

```

**Comment by cmelgarejo** [comment]
Yeah, I did too, but when you select a table with jsonb data, the poison library fails to parse the binary data, that's what I meant :(

-----Mensaje original-----
De: "zipme" <notifications@github.com>
Enviado el: ‎13/‎03/‎2015 23:31
Para: "ericmj/postgrex" <postgrex@noreply.github.com>
CC: "Christian Melgarejo Bresanovich" <christian.melgarejo.bresanovich@gmail.com>
Asunto: Re: [postgrex] (ArgumentError) no extension found for oid (#60)

@cmelgarejo I use the example code in README:
defmodule Extensions.JSON do
  alias Postgrex.TypeInfo

  @behaviour Postgrex.Extension
  @json ["json", "jsonb"]

  def init(_parameters, opts),
    do: Keyword.fetch!(opts, :library)

  def matching(_library),
    do: [type: "json", type: "jsonb"]

  def format(_library),
    do: :binary

  def encode(%TypeInfo{type: type}, map, _state, library) when type in @json,
    do: library.encode!(map)

  def decode(%TypeInfo{type: type}, json, _state, library) when type in @json,
    do: library.decode!(json)
end

**Comment by zipme** [comment]
@cmelgarejo 

Try this:

```
defmodule JSONB do
  alias Postgrex.TypeInfo

  @behaviour Postgrex.Extension

  def init(_parameters, opts),
    do: Keyword.fetch!(opts, :library)

  def matching(_library),
    do: [type: "jsonb"]

  def format(_library),
    do: :text

  def encode(%TypeInfo{type: "jsonb"}, map, _state, library),
    do: library.encode(map)

  def decode(%TypeInfo{type: "jsonb"}, json, _state, library),
    do: library.decode(to_string(json), keys: :atoms)

end

```

**Comment by cmelgarejo** [comment]
@zipme thanks! worked like a charm! jsonb needed to be decoded as TEXT instead of binary kind of beats the concept :confused:

**Comment by ericmj** [comment]
You should use the binary format whenever you can because then postgrex can encode/decodes higher types of it (such as arrays and composite types).  binary format jsonb sends a single byte with the version before the json so you can just pattern match that away and then call your json library.

```elixir
defmodule Extensions.JSON do
  alias Postgrex.TypeInfo

  @behaviour Postgrex.Extension
  @json ["json", "jsonb"]

  def init(_parameters, opts),
    do: Keyword.fetch!(opts, :library)

  def matching(_library),
    do: [type: "json", type: "jsonb"]

  def format(_library),
    do: :binary

  def encode(%TypeInfo{type: "json"}, map, _state, library),
    do: library.encode!(map)
  def encode(%TypeInfo{type: "jsonb"}, map, _state, library),
    do: <<1, library.encode!(map)::binary>>

  def decode(%TypeInfo{type: "json"}, json, _state, library),
    do: library.decode!(json)
  def decode(%TypeInfo{type: "jsonb"}, <<1, json::binary>>, _state, library),
    do: library.decode!(json)
end
```

I've also updated the README.

**Comment by zipme** [comment]
@ericmj  Thanks for the explanation!
@cmelgarejo You should use the above code instead, it works for me.

**Comment by cmelgarejo** [comment]
Works even better now! :) 

Thanks alot @ericmj and @zipme ! :beers:
