### ISSUE TITLE
Support query-specific extensions in postgrex

### ISSUE THREAD

**Issue by MSch** [ericmj/postgrex#65]
There should be a way to enable certain extensions only for certain queries:

```elixir
query("SELECT $1", ["=(integer, integer)"], extensions: [MyQuerySpecificExtension])
```

**Comment by josevalim** [comment]
I think this makes it very hard to cache. Can't you do it per connection?

**Comment by MSch** [comment]
Unfortunately not, the whole point is about having some extensions enabled only for some queries.

Isn't caching this as easy as adding the `extensions` to the cache key?

**Comment by ericmj** [comment]
It assumes that the postgres types the extension needs are already fetched and cached. This is specifically to override other extensions, if the extension adds new types it should just be added to the initial list of extensions.

If needed we can verify that the extension doesn't try to add new types.

**Comment by fishcakez** [comment]
As an alternative could you make use of `encode_mapper`/`decode_mapper` in #128? We can allow use of these in Ecto 2.0 as Ecto will need these.

**Comment by MSch** [comment]
My orginal use case was that I optionally wanted to send `regclass`/`regname` using text encoding, to make queries using them work like they do in `psql` or Rails. But I think the workaround described in [the README](https://github.com/ericmj/postgrex#oid-type-encoding) works fine, and Postgrex even links the user to the documentation of this caveat when they run into this problem.

So from my side I don't have any use case for that feature any more.

**Comment by ericmj** [comment]
Since this becomes even more complicated with type caching I am closing this.
