### ISSUE TITLE
Support all steps of extended query (parse / bind / execute)

### ISSUE THREAD

**Issue by ericmj** [ericmj/postgrex#7]

**Comment by zkat** [comment]
Hey, I created elixir-lang/ecto#493 -- This issue doesn't have much of a description but if it's what I think it is, it sounds like it would expose the bits needed for Ecto to support streamed results?

**Comment by ericmj** [comment]
Yes, the idea is to make the three steps of extended query public functions.

**Comment by fishcakez** [comment]
Added in https://github.com/ericmj/postgrex/commit/a7b951ca4e76f792a4ae087047ca3016c969bf39
