### ISSUE TITLE
Improve error message when encoding big numbers but column is not bigint

### ISSUE THREAD

**Issue by josevalim** [ericmj/postgrex#72]
See https://github.com/elixir-lang/ecto/issues/602.

**Comment by ericmj** [comment]
Encoding errors seem to produce enormous FunctionClause errors so we should add a pokemon clause that generates a nicer error message. The failing oid and inspected term should be enough for the message and if possible also translate the oid to a type name).

**Comment by jarkko** [comment]
+1. I just ran into this when trying to insert a `Date.now` timestamp from JS to an integer column. Took a while to figure out what was going on.

**Comment by josevalim** [comment]
Maybe it is better to move the encoding to the client, to avoid blocking the connection process and avoid crashing the connection.

**Comment by ericmj** [comment]
We can't encode in the client because we need type information from the server first. We can wrap the encoding in try/catch and just log the error though.

**Comment by josevalim** [comment]
We need this to be high priority. It is confusing for a lot of users, I will work on this now.
