### ISSUE TITLE
Discuss caching of type data

### ISSUE THREAD

**Issue by josevalim** [ericmj/postgrex#73]
Today each postgrex connections needs to query the db when it is started. It would be nice to cache this information and have each connection retrieving it locally instead of hitting the db on load.

**Comment by ericmj** [comment]
Was this found to be an issue? We can only cache the query result itself, connections still need to store the same amount of data on the heap.

**Comment by ericmj** [comment]
Even the query is tricky to cache because it depends on the connection options.

We will also need to way to explicitly reload the cache since the database can change.
