### ISSUE TITLE
Postgrex 0.8.3 causes failures when running migrations with ecto 0.12.0 on travis ci

### ISSUE THREAD

**Issue by drewolson** [ericmj/postgrex#81]
Failing build after upgrading ecto to 0.12.0 and postgrex to 0.8.3 -- https://travis-ci.org/drewolson/scrivener/builds/68021116

Successful build after downgrading postgrex back to 0.8.2 -- https://travis-ci.org/drewolson/scrivener/builds/68025222

Please let me know if you need more information.

**Comment by josevalim** [comment]
Can you upgrade to postgrex 0.8.3 and then run mix deps.clean postgrex (or just nuke `_build`)?

**Comment by drewolson** [comment]
@josevalim isn't the `_build` folder clean on every build because this is running on travis? It works locally with both versions.

**Comment by josevalim** [comment]
Ah, yes. I have no idea why this is happening.

**Comment by josevalim** [comment]
Ok, apparently this error is happening since 0.8.3 release in postgrex builds themselves: https://travis-ci.org/ericmj/postgrex/jobs/67859407

**Comment by ericmj** [comment]
Seems to be an issue with the version detection that I didn't get when testing locally. Will look into it.
