### ISSUE TITLE
JSON encoder should be a no-op in postgres versions that do not support 

### ISSUE THREAD

**Issue by josevalim** [ericmj/postgrex#82]
Currently, using the JSON type will break Postgrex on versions 9.1 and earlier. The type should not cause errors on postgres versions that do not support it.

**Comment by ericmj** [comment]
The JSON encoder should only run if the server is actually asking the client to encode json, which it of course shouldn't if it doesn't support it.

**Comment by ericmj** [comment]
Is this is an actual bug? I don't see how this is a postgrex bug, if the json type isn't supported the server should return an error response. Do you remember what the issue was?
