### ISSUE TITLE
Postgrex is breaking the connection when a query fails

### ISSUE THREAD

**Issue by josevalim** [ericmj/postgrex#88]
Maybe all queries fail like that but I was reproducing the bug by following all steps except step 6 here: https://github.com/elixir-lang/ecto/issues/781

The root of the bug in that issue is that the database does not exist when making the query. I am assuming that this particular kind of query fails early on, trigger some bits in Postgrex internals it was not supposed to.

**Comment by ericmj** [comment]
This is not a bug.The query is failing because the connection is connecting to a database that doesn't exist. It would fail before the query is run if the connection set up was synchronous which is the new default.
