### ISSUE TITLE
Postgres.Messages.parse breaking on very large query

### ISSUE THREAD

**Issue by dmarkow** [ericmj/postgrex#96]
I have a very large query I'm running that is causing the following error:

```
** (FunctionClauseError) no function clause matching in Postgrex.Messages.parse/3
    (postgrex) lib/postgrex/messages.ex:52: Postgrex.Messages.parse(<<129, 230, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, ...>>, 116, 133018)
    (postgrex) lib/postgrex/connection.ex:416: Postgrex.Connection.new_data/2
    (postgrex) lib/postgrex/connection.ex:292: Postgrex.Connection.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:tcp, #Port<0.109833>, <<49, 0, 0, 0, 4, 116, 0, 2, 7, 158, 129, 230, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, ...>>}
```

The [function clause](https://github.com/ericmj/postgrex/blob/master/lib/postgrex/messages.ex#L83) that __should__ be matching is this:

```elixir
  def parse(<<len :: int16, rest :: binary(len, 32)>>, ?t, _size) do
    oids = for <<oid :: size(32) <- rest>>, do: oid
    msg_parameter_desc(type_oids: oids)
  end
```

However, parsing `<<129,230>>` as `int16` actual overflows and returns a negative number (-32,282). If I change the function definition to use `uint16` instead, it makes `len` 33,254, which makes the function clause match, as `rest` properly matches on 33,254 * 4 bytes (133,016), which then matches the `_size` parameter of 133,018 (133,016 plus 2 bytes for `len`).

Note that I'm running this from Ecto 1.0.4, Elixir 1.1.1, and Postgres 9.4.4

**Comment by ericmj** [comment]
Thank you for the bug report and finding the cause of the error. Are you sending a PR for the fix or should I do it?
